version: "3.7"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - ./scripts/postgres/pg-init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./.docker/pg:/var/lib/postgresql/data
    ports:
      - "$PG_PORT:5432"
  redis:
    image: bitnami/redis
    env_file:
      - .env
    environment:
     REDIS_PORT: $REDIS_PORT
     ALLOW_EMPTY_PASSWORD: true
    ports:
      - "$REDIS_PORT:6379"

